// Codex-style bottom pane view model for tiffany-loop lightweight terminal runner.
//
// The upstream UI source implementation lives in:
// third_party/openai-codex/codex-rs/tui/src/bottom_pane/
//
// This module keeps the same ownership boundary: status, transient hints,
// queue preview, and prompt text are generated by a bottom-pane component
// instead of being embedded in the terminal event loop.

use super::queue_state::QueueSnapshot;
use super::state::InputState;
use super::util::truncate_chars;
use crate::runtime;
use std::time::Duration;
use std::time::Instant;
use unicode_width::{UnicodeWidthChar, UnicodeWidthStr};

const RESET: &str = "\x1b[0m";
const DIM: &str = "\x1b[2m";
const BOLD: &str = "\x1b[1m";
const TIFFANY: &str = "\x1b[38;2;129;216;208m";
const CYAN: &str = TIFFANY;
const GREEN: &str = TIFFANY;
const YELLOW: &str = "\x1b[33m";
const TERMINAL_QUEUE_PREVIEW_LIMIT: usize = 4;

pub(super) fn status_lines(
    input: &InputState,
    active: bool,
    spinner_started_at: Option<Instant>,
    terminal_width: usize,
) -> Vec<String> {
    let (icon, color, mut segments) = if active {
        let frames = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];
        let idx = spinner_started_at
            .map(|started| ((started.elapsed().as_millis() / 120) as usize) % frames.len())
            .unwrap_or(0);
        let mut segments = vec![stage_label(input)];
        if let Some(started) = spinner_started_at {
            segments.push(format!("{} elapsed", format_elapsed(started.elapsed())));
        }
        (frames[idx], CYAN, segments)
    } else {
        let mut segments = vec!["ready".to_string()];
        if !input.current_stage.trim().is_empty() {
            segments.push(format!("last {}", input.current_stage.trim()));
        }
        ("✓", GREEN, segments)
    };

    segments.extend(status_context_segments(input, active));
    let plain = segments
        .into_iter()
        .filter(|segment| !segment.trim().is_empty())
        .collect::<Vec<_>>()
        .join(" · ");
    let available = terminal_width.saturating_sub(2).max(16);
    let plain = truncate_display_width(&plain, available);
    vec![format!("{color}{icon}{RESET} {DIM}{plain}{RESET}")]
}

fn stage_label(input: &InputState) -> String {
    let stage = if input.current_stage.trim().is_empty() {
        "starting"
    } else {
        input.current_stage.trim()
    };

    if input.current_stage_detail.trim().is_empty() {
        stage.to_string()
    } else {
        format!("{} — {}", stage, input.current_stage_detail.trim())
    }
}

fn status_context_segments(input: &InputState, active: bool) -> Vec<String> {
    let mut segments = Vec::new();

    if active {
        if let Some(flow) = input
            .run_route_label
            .as_deref()
            .map(str::to_string)
            .or_else(|| input.run_route.as_deref().map(flow_label))
        {
            segments.push(format!("flow {flow}"));
        }
    } else if let Some(flow) = input
        .run_route_label
        .as_deref()
        .map(str::to_string)
        .or_else(|| input.run_route.as_deref().map(flow_label))
    {
        segments.push(format!("last flow {flow}"));
    }
    if let Some(reason) = input
        .run_route_reason_label
        .as_deref()
        .map(str::to_string)
        .or_else(|| input.run_route_reason.as_deref().map(route_reason_label))
    {
        if !reason.is_empty() {
            segments.push(format!("reason {reason}"));
        }
    }

    segments.push(format!(
        "worker {}",
        runtime::agent_label(input.agent_hint.as_deref())
    ));
    segments.push(context_segment(input));

    if !input.queued_prompts.is_empty() {
        let queue = QueueSnapshot::from_input(input, TERMINAL_QUEUE_PREVIEW_LIMIT);
        segments.push(format!("queue {} {}", queue.count, queue.status_label()));
    }

    if active {
        segments.push(if input.history_folded {
            "detail folded /o".into()
        } else {
            "detail full /o".into()
        });
        if let Some(filter) = input.process_filter.as_deref() {
            segments.push(format!("filter {}", truncate_chars(filter, 18)));
        }
    } else {
        segments.push("/ for commands".into());
    }

    if input.run_review_issue_count > 0 {
        segments.push(format!("review {} issue(s)", input.run_review_issue_count));
    }
    if input.run_review_unavailable_count > 0 {
        segments.push(format!(
            "review unavailable {}",
            input.run_review_unavailable_count
        ));
    }
    if input.run_worker_failure_count > 0 {
        segments.push(format!("worker {} failed", input.run_worker_failure_count));
    }

    segments
}

fn flow_label(route: &str) -> String {
    crate::agent_events::OrchestrationRoute::from_label(route)
        .map(|route| route.display_label().to_string())
        .unwrap_or_else(|| truncate_chars(route, 18))
}

fn route_reason_label(reason: &str) -> String {
    let reason = reason.trim();
    if reason.is_empty() {
        return String::new();
    }
    crate::agent_events::OrchestrationRoute::reason_display_label(reason)
        .map(str::to_string)
        .unwrap_or_else(|| truncate_chars(reason, 32))
}

fn context_segment(input: &InputState) -> String {
    if input.last_context_messages > 0 {
        format!(
            "ctx {} {} msg/{} chars",
            input.context_mode.as_str(),
            input.last_context_messages,
            input.last_context_chars
        )
    } else {
        format!("ctx {}", input.context_mode.as_str())
    }
}

pub(super) fn hint_lines(input: &InputState, active: bool, terminal_width: usize) -> Vec<String> {
    if slash_completion_active(input) {
        return Vec::new();
    }

    let hint = if active {
        if input.queued_prompts.is_empty() {
            "Enter queues follow-up · /o detail · /process 200 logs · /cancel stop"
        } else if input.queue_paused {
            "queue paused · /queue resume · /queue edit n text · /cancel stop"
        } else {
            "follow-ups queued · /queue pause · /queue edit n text · /cancel stop"
        }
    } else if !input.queued_prompts.is_empty() {
        if input.queue_paused {
            "queue paused · /queue resume or /queue run · /queue show"
        } else {
            "queue ready · /queue run · /queue pause · /queue show"
        }
    } else if input.buffer.trim_start().starts_with('/') {
        "↑↓ select · Enter accept/run · Esc close · /help"
    } else if input.last_result_output.is_some() {
        "/ for commands · /result text · /copy result · /doctor"
    } else {
        "/ for commands · ↑↓ history · /doctor · /help"
    };

    let available = terminal_width.saturating_sub(2).max(16);
    vec![format!(
        "{DIM}{}{}",
        truncate_display_width(hint, available),
        RESET
    )]
}

fn slash_completion_active(input: &InputState) -> bool {
    if input.slash_completion_dismissed || input.cursor != input.buffer.len() {
        return false;
    }

    let trimmed = input.buffer.trim_start();
    trimmed.starts_with('/') && !trimmed.contains('\n')
}

pub(super) fn queue_lines(input: &InputState, terminal_width: usize) -> Vec<String> {
    if input.queued_prompts.is_empty() {
        return Vec::new();
    }

    let queue = QueueSnapshot::from_input(input, TERMINAL_QUEUE_PREVIEW_LIMIT);
    let content_width = terminal_width.saturating_sub(6).max(20);
    let status_color = if queue.paused { YELLOW } else { GREEN };
    let status = format!("{status_color}{}{RESET}", queue.batch_label());
    let mut lines = vec![format!(
        "{CYAN}{BOLD}queue{RESET} {status} {DIM}{} item(s), runs together{RESET}",
        queue.count
    )];

    for item in &queue.preview {
        let label = format!("↳ {}. ", item.index);
        let continuation = " ".repeat(label.chars().count());
        let wrapped = wrap_text_lines(&item.text, content_width.saturating_sub(label.len()));
        for (line_idx, line) in wrapped.iter().enumerate() {
            if line_idx == 0 {
                lines.push(format!("  {CYAN}{label}{RESET}{line}"));
            } else {
                lines.push(format!("  {continuation}{line}"));
            }
        }
    }

    if queue.hidden_count > 0 {
        lines.push(format!(
            "  {DIM}+ {} more queued; /queue show for full batch{RESET}",
            queue.hidden_count
        ));
    }

    lines
}

pub(super) fn wrap_text_lines(prompt: &str, width: usize) -> Vec<String> {
    let width = width.max(12);
    let mut rows = Vec::new();

    for source_line in prompt.lines() {
        let mut current = String::new();
        let mut current_width = 0;
        for ch in source_line.chars() {
            let char_width = UnicodeWidthChar::width(ch).unwrap_or(0);
            if current_width > 0 && current_width + char_width > width {
                rows.push(current);
                current = String::new();
                current_width = 0;
            }
            current.push(ch);
            current_width += char_width;
        }
        rows.push(current);
    }

    if rows.is_empty() {
        rows.push(String::new());
    }
    rows
}

pub(super) fn prompt_plain(active: bool) -> &'static str {
    if active {
        concat!("\x1b[36m", "queued>", "\x1b[0m", " ")
    } else {
        concat!("\x1b[36m", ">", "\x1b[0m", " ")
    }
}

pub(super) fn buffer_view(buffer: &str, cursor: usize, max_width: usize) -> String {
    if UnicodeWidthStr::width(buffer) <= max_width {
        return buffer.to_string();
    }

    let cursor = clamp_cursor(buffer, cursor);
    let prefix = &buffer[..cursor];
    let suffix = &buffer[cursor..];
    let suffix_width = UnicodeWidthStr::width(suffix);
    if suffix_width >= max_width.saturating_sub(1) {
        return truncate_display_width(buffer, max_width);
    }

    let mut out = String::new();
    let mut width = suffix_width + UnicodeWidthStr::width("…");
    for ch in prefix.chars().rev() {
        let char_width = UnicodeWidthChar::width(ch).unwrap_or(0);
        if width + char_width > max_width {
            break;
        }
        out.insert(0, ch);
        width += char_width;
    }
    out.insert(0, '…');
    out.push_str(suffix);
    truncate_display_width(&out, max_width)
}

pub(super) fn truncate_display_width(text: &str, max_width: usize) -> String {
    if UnicodeWidthStr::width(text) <= max_width {
        return text.to_string();
    }

    let ellipsis_width = UnicodeWidthStr::width("…");
    let target = max_width.saturating_sub(ellipsis_width);
    let mut out = String::new();
    let mut width = 0usize;
    for ch in text.chars() {
        let char_width = UnicodeWidthChar::width(ch).unwrap_or(0);
        if width + char_width > target {
            break;
        }
        out.push(ch);
        width += char_width;
    }
    out.push('…');
    out
}

fn clamp_cursor(buffer: &str, cursor: usize) -> usize {
    let mut cursor = cursor.min(buffer.len());
    while cursor > 0 && !buffer.is_char_boundary(cursor) {
        cursor -= 1;
    }
    cursor
}

fn format_elapsed(duration: Duration) -> String {
    let secs = duration.as_secs();
    if secs < 60 {
        format!("{}s", secs)
    } else {
        format!("{}m{:02}s", secs / 60, secs % 60)
    }
}
