[package]
name = "tiffany-bridge"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "tiffany_bridge"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
tiffany-event-format = { path = "../../../crates/tiffany-event-format" }

[dev-dependencies]
tempfile = { workspace = true }
